site_name: Engenharia de Dados SATC
site_description: Documentacao do projeto <nome do projeto>
site_author: Jorge Luiz da Silva
site_url: https://jlsilva01.github.io/projeto-ed-satc

repo_name: projeto-ed-satc
repo_url: http://github.com/jlsilva01/projeto-ed-satc
edit_uri: edit/master/docs/

docs_dir: docs

nav:
  - Home: index.md
  - Sobre: sobre.md
  - Pipeline de Dados: pipeline.md

theme:
  name: material
  palette:
    primary: blue
    accent: light-blue
  language: pt
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    #- navigation.paging
    #- navigation.expand
    - navigation.top
    #- navigation.sidebar
    - navigation.next-prev
    #- navigation.toc
    #- navigation.scrollspy
    - search
  icon:
    repo: fontawesome/brands/github
  favicon: images/favicon.png
  logo: images/logo.png

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://jl2tech.com
  generator: false

copyright: Copyright &copy; 2024 - <a href="#" target="_blank"><b>Jorge Luiz da Silva</b></a> - Todos os direitos reservados.

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
