site_name: System Transport Delta Lake Eng.Dados UniSatc
site_description: Documentacao do projeto SystemTransportDeltaLake
site_author: Jorge Luiz da Silva
site_url: https://brunosupriano.github.io/SystemTransportDeltaLake/
site_keywords: Engenharia de Dados, Engenharia de Software, SATC, Python, Pyspark, Delta, Jupyter, Git, GitHub, Markdown, MkDocs, Material Theme

repo_name: SystemTransportDeltaLake
repo_url: https://github.com/BrunoSupriano/SystemTransportDeltaLake
edit_uri: edit/master/docs/

docs_dir: docs

nav:
  - Home: index.md
  - Equipe: equipe.md
  - Como começar: initial_commands.md
  - Pipeline de Dados:
      - Oque é?: about_pipeline.md
      - Arquitetura: pipeline.md
      - Bronze: pipeline_bronze.md
      - Silver: pipeline_silver.md
      - Gold: pipeline_gold.md
  - Conclusão: conclusion.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  language: pt
  features:
    - navigation.footer
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    #- navigation.paging
    #- navigation.expand
    - navigation.top
    #- navigation.sidebar
    - navigation.next-prev
    #- navigation.toc
    #- navigation.scrollspy
    - search
  icon:
    repo: fontawesome/brands/github
  favicon: images/favicon.png
  logo: assets/logo-1.jpg

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://jl2tech.com
  generator: false

copyright: Copyright &copy; 2024 - <a href="#" target="_blank"><b>SystemTransportDeltaLake</b></a> - Todos os direitos reservados.

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
